import { type NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import BubbleDetail from "../components/BubbleDetail";
import { io } from "socket.io-client";
import { useEffect, useState } from "react";

type Message = {
	username: string;
	avatar: string;
	roles?: string[];
	channel: {
		name: string;
		description: string;
	};
	text: string;
	timestamp: string;
};

const Home: NextPage = () => {
	const [messages, setMessages] = useState<Message[]>([]);

	useEffect(() => {
		const socket = io("http://localhost:3001");

		socket.on("connect", () => {
			console.info("Connected");
		});

		socket.on("disconnect", () => {
			console.info("Disconnected");
		});

		socket.on("message", (message: Message) => {
			setMessages(prevMessages => [...new Set([...prevMessages, message])]);
		});

		return () => {
			socket.disconnect();
		};
	}, []);

	return (
		<>
			<Head>
				<title>Code Crusaders</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className={styles.background}>
				<BubbleDetail></BubbleDetail>
				{messages.map((message, i) => (
					<div key={parseFloat(message.timestamp) + i} className="text-white">
						<h1>{message.text}</h1>
					</div>
				))}
			</main>
		</>
	);
};

export default Home;
